### ISSUE TITLE
PUHLEEZE keep the "File System" database option in place.

### ISSUE THREAD

**Issue by dnlombard** [perfectapi/CKP#102]
I fundamentally rely on local files for KeepPass on my home Linux workstation, work Windows laptop, android phone, and now Chromebook. I greatly prefer the minor inconvenience of manual file sync v. keeping my password DB on Google drive, dropbox, onedrive, or any other such globally accessible file store. :)

**Comment by thelollies** [comment]
It looks like it's staying: https://github.com/perfectapi/CKP/issues/97

Might pay to change the wording around it so there's less confusion.

**Comment by DukeyToo** [comment]
Closing this issue.  I "undid" the deprecation and changed the wording.
