### ISSUE TITLE
Unable to select database

### ISSUE THREAD

**Issue by koffiejunk** [perfectapi/CKP#106]
I've tried to select a keepass database. Instead i'm redirected to the chrome://extensions page.
I'm unable to select the database and with that, CKP is basically useless in this state. What information do you need to fix it?
![knipsel](https://cloud.githubusercontent.com/assets/20065581/16227555/8dce8fd4-37b1-11e6-84be-e922f875e345.PNG)

**Comment by DukeyToo** [comment]
Are you saying that you don't see the options page?  I would need to know what version of Chrome you are using.

**Comment by koffiejunk** [comment]
At that time i would have used version 51.0.2704. I think it had something to do with a custom setting I enabled. I've had enabled the Material Design-extention in chrome://flags.

Right now it seems to be working.

**Comment by DukeyToo** [comment]
ok, thanks.  I tried enabling some of the material design flags and was unable to reproduce.  Closing.
