### ISSUE TITLE
Unable to locate .kbdx file in Google Drive

### ISSUE THREAD

**Issue by mphartzheim** [perfectapi/CKP#113]
I've used a .kbdx file in my Google Drive for awhile now, just installed CKP and after authorizing my Google Drive it gives me the following error message:

CKP has accessed your drive but could not find any password files. Ensure your .kdbx or .kdb file is in your google drive.

I had the .kbdx file in a subfolder at first and thought that may be the issue. I moved it to the root of my Google Drive and I still get the same error.

**Comment by DukeyToo** [comment]
Subfolders should not matter.  CKP executes a search on your remote drive for files ending in `.kdb` or `.kdbx`.  I can't think of a reason it would not find the file with a correct extension.

**Comment by mphartzheim** [comment]
Well, not sure what's going on then. I've tried creating a new database, tried deauthorizing and reauthorizing the extension, and tried reinstalling the extension. Everything results in the same error message.

**Comment by mphartzheim** [comment]
Looks like my database was at least partially corrupted. The "Type" displayed in File Explorer simply said "KBDX Extension" while an older version of the file that I had said "KeePass Database" as the file type.

I uploaded this older file to my google drive and CKP found it no problem.
