### ISSUE TITLE
CKP: Local Database deprecated

### ISSUE THREAD

**Issue by AllenLStarr** [perfectapi/CKP#114]
This is NOT an issue; consider it feedback.
I would appreciate it if the local file option was not deprecated.  My Keepass database is protected by a long master password but I still don't want to place it in the cloud.  I am ok with updating the Keepass database on my Windows computer, encrypting it with miniLock, posting it to the cloud, and decrypting to a Chromebook local file it with minilock,  I think your warnings that local files are not automatically updated is sufficient to alert individuals of the tradeoff between the simplicity of cloud storage vs the security of local storage.

**Comment by gwillen** [comment]
I agree completely. I'm using this extension for KeePass support on my new Chromebook, and it would be a problem if I could no longer use it with a local file, as I am not willing to store my keepass database in Drive or Dropbox (I'm fine having it cached in localstorage on the chromebook.) I understand that the file won't update automatically -- that's fine as it doesn't change often anyway.

**Comment by gwillen** [comment]
Yay, thanks! :-) 👍
