### ISSUE TITLE
Doesn't dereference referenced entries

### ISSUE THREAD

**Issue by hydrian** [perfectapi/CKP#121]
If you duplicate an entry in keepass2, you can use references for username and password. This is great for multiple sites that use the same credentials. Example: Amazon.com and Audilble.com

If you try autofill or copy the credentials from CKP from a referenced account, you get the reference ID and not the resolved value. 

See the link below for more info:
http://keepass.info/help/base/fieldrefs.html

**Comment by DukeyToo** [comment]
Closing, this is a duplicate of #28
