### ISSUE TITLE
Chrome Extension only checks general folder

### ISSUE THREAD

**Issue by markediez** [perfectapi/CKP#124]
Any entry outside of the general folder is not seen through the extension automatically or manually. As a concrete example, I have an entry located at homebanking and a custom folder and I cannot find it through the extension even though it is on the kdbx file.

Tried it through google drive and the deprecated local file way.

**Comment by DukeyToo** [comment]
The extension does a Google Drive search on the whole drive - it should find it irrespective of the folder. 

Sometimes when you make a change on the local Google Drive copy, that change is not immediately reflected on the Google Drive on the server.   I recommend you use the web interface to Google Drive and verify that the file is actually present in the location that you think it should be.

**Comment by markediez** [comment]
~~Oh, It finds the .kdbx file in google drive. What I mean is that once I load the .kdbx file in the extension, it only parses the entries from the general folder~~

If I delete all the *Stored Data* Entries in the extension, I can see all my passwords. I guess the real bug is that its not invalidating the cache properly when the database updates.

**Comment by DukeyToo** [comment]
And this is why the "local file way" is deprecated.  It just confuses people.
