### ISSUE TITLE
CTRL+SHIFT+SPACE cannot be disabled

### ISSUE THREAD

**Issue by doug144** [perfectapi/CKP#131]
I need to disable the CTRL+SHIFT+SPACE shortcut on my chromebook, since that is also the system shortcut to switch the keyboard language. Please add an option to disable the shortcut

**Comment by DukeyToo** [comment]
Go to chrome://extensions/ , scroll down to the bottom and click on the Keyboard Shortcuts link.  You can change shortcuts for any extension there.
