### ISSUE TITLE
Handle expired entries meaningfully

### ISSUE THREAD

**Issue by mathphreak** [perfectapi/CKP#133]
Generally, when I change my password on a site I keep the old password around in my KeePass database just in case and I mark it as expired. However, the CKP UI doesn't show expired entries any different from non-expired entries, so I have to just guess which one is the most recent one.

It looks like there's already a bit of [code for parsing expiration](https://github.com/perfectapi/CKP/blob/0c4b2f172f3d1a0badff70f5e36d1dc562e0e444/services/keepassService.js#L305) and it's just a matter of exposing that in the entry details UI (and potentially also the password list UI).

**Comment by DukeyToo** [comment]
So this is the older kdb file format?

**Comment by mathphreak** [comment]
No, it's a kdbx. So I guess the code I linked to isn't actually the right code.

**Comment by suBDavis** [comment]
Fix suggested in #168

**Comment by subdavis** [comment]
This issue was resolved in #168 and can be closed.
