### ISSUE TITLE
Copied password is corrupted, containing unrecognized characters

### ISSUE THREAD

**Issue by michaelleinweaver** [perfectapi/CKP#138]
### Background

I noticed this issue after Chrome updated CKP with your commits from 11/26 and 11/27. I am using Chrome 54.0.2840.101 64 bit (latest version) and the older KDB file type.

### Issue

CKP is replacing alphanumeric characters in my stored passwords with the [Unicode replacement character](http://www.fileformat.info/info/unicode/char/fffd/index.htm). This issue can be observed both by inspecting the password through CKP and inspecting the copy-pasted password in a text editor. Inspecting the password through KeePass and older versions of CKP indicates that the database entry is not corrupted.

### Reproduction Steps

After Chrome updated CKP, I noticed the issue after performing the following steps:

1. Adding my KDB instance to the extension using the "Local File System" option.
2. Entering my master password like usual.
3. Copying my password from the extension. 
        - Side note: I had to click "Copy" several times to get the password to actually copy. I think there may be another JS issue here that's preventing the script from copying the password to the clipboard, but unfortunately I don't have any logs to attach to this post.
4. Pasting my copied password from step (3) and attempting to log in.

**Comment by ansonolds** [comment]
I am experiencing the same problem. I am running a chromebook with chrome OS and I use the CKP extension to manage my passwords. This happens both when I attempt to copy and paste or auto-fill password field, and when I view the password in the extension window. I noticed this problem occurring Nov. 27th at around 5:00 PM EST.

**Comment by somethingwittythiswaycomes** [comment]
I have the same problem as of today. 

Chrome OS on a Toshiba CB2 (Gandof). 
ChromeOS Version: Version 55.0.2883.54 beta (64-bit)

Started for me today 28.11.2016. Not sure when extension was last updated. Attempted to add and remove the extension, restart machine, etc. No joy. Assuming this is a bug with the latest version. I tried to find an older version of the extension, but was unable to load it as an unpacked extension. If you guys could link us to an older version, I would be happy to try it. 

I'm also using a *.kdb file, not a KeePass2 database, linked via DropBox.

**Comment by gngdb** [comment]
I have the same problem today. Chome OS version: 55.0.2883.54 beta. Also using `*.kdb` database.

**Comment by DukeyToo** [comment]
Reverted the PR that seems to have introduced this.  Let me know if version 2016.11.28 fixes the issue.

**Comment by michaelleinweaver** [comment]
@DukeyToo, the issue is still occurring for me. I reinstalled CKP and confirmed it's on version 2016.11.28 before adding my local database file and my passwords still have corrupted characters. I checked the developer console both when unlocking the database and copying entries and did not notice any error messages.

**Comment by DukeyToo** [comment]
Was able to reproduce - pretty sure it is fixed now.  You don't need to re-add your files or anything - the issue only affected the passwords when they were in-memory.

**Comment by somethingwittythiswaycomes** [comment]
Hi, 

For me it has been fixed with version 2016.11.29. 

Thanks a lot for all your work.

**Comment by michaelleinweaver** [comment]
The latest fix did the trick, thanks a lot!
