### ISSUE TITLE
Remembered password won't expire

### ISSUE THREAD

**Issue by dygordon** [perfectapi/CKP#143]
I've seen some weird behaviour on Google Chrome 49.0.2623.112 (64-bit) on OS X 10.8.5. Perhaps since the last update. I use a DB stored on Dropbox and CKP is setup to access Dropbox directly.

I have remember password set for 30 minute expiry. I've noticed of late (again perhaps since last update) that I return to my computer hours later and the DB will still auto-unlock without me entering the password. I have to go to the select DB interface and re-select my DB to have it close and lock it.

Normally when I am done using the computer I close the lid or switch to another user if that's pertinent.

So, I uninstalled and reinstalled CKP last night.

Just this AM, after logon, I started getting repeated "Password expired" notification boxes, infinitely regenerating.

I disabled the extension to stop this. And then I got a notification that Google Hangouts had an error and quit (I also use the Google Hangout extension). I recall that I saw this when I disabled and reinstalled CKP yesterday.

Not sure what the link is between quitting CKP and Hangouts crashing but there you go. Makes me a little nervous that there is some sort of malware using Hangouts as a conduit for my perpetually unlocked KPDB through CKP... But seems a little farfetched!

EDIT to add: Experimented a bit. If the DB is locked and password not remembered, enabling/disabling CKP does nothing to Hangouts. If the password is remembered, Hangouts crashes every time CKP is disabled in chrome://extensions/. Hangouts ver 2016.1108.1036.2

**Comment by DukeyToo** [comment]
If you look in CKP options / Stored Data tab, what do you see under `forgetTimes`?  For example, this is what I see when I have remembered the password for 30 mins this morning:

![capture](https://cloud.githubusercontent.com/assets/1268000/21081480/86d60acc-bf8d-11e6-9a6e-c8f360dd24cf.PNG)

I don't have any theories as to what could cause this behavior.  I have enabled the Hangouts app and have not reproduced the behavior yet.

If you want to be sure that everything is forgotten for now, you can delete `forgetTimes`, and also the `databaseUsages` key in the stored data.

**Comment by dygordon** [comment]
It was empty. Apparently the password was forgotten this time. And only got a single notification that the password had expired upon logon. I had Hangouts disabled.

After entering the key it becomes 'forgetPassword: 1481476746839'.

I will reenable Hangouts and see what happens this time around!

**Comment by dygordon** [comment]
Well, now I can't reproduce it either. Guess that's that!
