### ISSUE TITLE
Cannot Authorize Google Drive

### ISSUE THREAD

**Issue by usc1787** [perfectapi/CKP#145]
Hello,

I just installed the extension. However, when I click on the google drive option under keepass databases it opens a google login page. When I login it just brings me to a blank white page "vivaldi://chrome-signin/?access_point=6&reason=0". There is no dialog tell me to please press "Accept". Any help would be greatly appreciated - Thank You

**Comment by DukeyToo** [comment]
Vivaldi?

**Comment by DukeyToo** [comment]
Closing - Vivaldi is not supported.
