### ISSUE TITLE
KeepassX kdbx Database never loaded into CKP

### ISSUE THREAD

**Issue by trystant** [perfectapi/CKP#153]
Hi,

I'm running CKP on a Chromebook Pixel (2013). When I go to the CKP Options page, it gives me the option of finding my kdbx file through all the correct channels. If I select Google Drive, I give the app permission to access my Google Drive. It then finds my 'whatsmine.kdbx' file, but there is no option to enter my master password when I go to the test page or any other site. This screenshot is the last thing I see.

![screenshot 2017-01-23 at 5 28 06 am](https://cloud.githubusercontent.com/assets/13509/22200401/d28f9800-e113-11e6-862a-17bd367e630f.png)

The database was created using KeepassX and is a kdbx file. Let me know if there's any other information needed. Thanks.

**Comment by DukeyToo** [comment]
In the top right of Chrome, there may be a set of vertical `...` that is hiding a bunch of extension icons.   Try clicking on that and see if you can see the CKP icon.  If you can, then right click on it and choose "Show in toolbar".

**Comment by trystant** [comment]
Yup, that worked. I see the Keepass icon and now everything's working as expected. Thanks.
