### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by JeremyWW** [perfectapi/CKP#155]
Any plans for a Firefox port?

Thanks

**Comment by gynet** [comment]
Please

**Comment by DukeyToo** [comment]
Nope, no plans for this.

**Comment by Jeffrey04** [comment]
since firefox now support webextensions api, will this ever happen?

**Comment by gerardo-junior** [comment]
I would love to see this extension as an addon in firefox since I only see keepassxHTTP
