### ISSUE TITLE
reload local database file regulary

### ISSUE THREAD

**Issue by taaz** [perfectapi/CKP#159]
Since I couldn't find a similar suggestion, I would like to suggest to reload the database file, stored locally, regulary. It can be pretty annoying to "upload" the file after every change.

background: not everybody uses one of the supported clouds (I personally use ownCloud). So the file is always synced but the browser doesn't recognize new or changed entries which is really sad.

**Comment by txmoose** [comment]
I believe someone mentioned supporting WebDAV in another thread. That would be the most robust solution, as many clouds, NAS's, etc can provide WebDAV pretty readily. I personally use Nextcloud, and the Android app Keepass2Android supports it beautifully.

**Comment by DukeyToo** [comment]
As mentioned by @txmoose , the webdav PR https://github.com/perfectapi/CKP/pull/98 is probably your best bet
