### ISSUE TITLE
Google Drive: "The user is not signed in"

### ISSUE THREAD

**Issue by EddieCrosbie** [perfectapi/CKP#161]
When I try to access google drive from the settings, I receive an error that says "user is not signed in", although I'm logged in to both my Chrome account and my drive.
I made sure to choose "Accept" to allow keePass to view my files in Google Drive.
I'm using Google Chrome on a Chromebook.

**Comment by DukeyToo** [comment]
Do you have multiple Google accounts?   Perhaps you are logged into one account in Chrome and another in CPK?

**Comment by EddieCrosbie** [comment]
I believe I was correctly logged into a specific account. After I had this issue I successfully synced it with drive from my desktop, and it now appears to also work on the Chromebook.
Thanks for a great product!

**Comment by DukeyToo** [comment]
Excellent, thanks!
