### ISSUE TITLE
Passwords lost

### ISSUE THREAD

**Issue by fotosmotos** [perfectapi/CKP#162]
CKP for chrome was syncronized to google drive, everything was working, file .kdbx was located on the google drive, adding of password to the file automaticly brings it to CKP.

After deleting CKP from chrome and adding again, file at google drive was replaced to the old one and all new passwords stored for a half of year were lost.
I also cannot find any .kdbx file at the PC locally (thought may be CKP store it temporaly at the drive).

**Comment by DukeyToo** [comment]
CKP does not use any APIs thaqt can write or erase data from your Google Drive.  If you lost your passwords, thats on you.
