### ISSUE TITLE
Cannot authorize google drive

### ISSUE THREAD

**Issue by npgauth** [perfectapi/CKP#167]
CKP was working perfectly until this afternoon when I had some bad sync problems with google drive. I thought deauthorization and reauthorization would fix the problem, but it did not. Low and behold it was a problem on google's end (other sync software also didn't work).

Now I have a new problem--when I try to add the google drive database, no dialog ever pops up requesting permission from google. There is just text indicating "CKP needs to view the files in your Google Drive in order to continue. Please press "Accept" on the dialog.".

Any idea how to solve this problem?

Thanks, Nick

**Comment by suBDavis** [comment]
This problem was likely due to the google drive downtime today.

Google drive went down earlier.  Please try accessing drive.google.com and browsing to your keepass db.  IF that works, try deauth/reauth again.

**Comment by suBDavis** [comment]
Indeed Drive was down today: Outage here: https://www.google.com/appsstatus#hl=en&v=issue&sid=4&iid=c708d68b1884a629816e361895c125a5

Disable CKP from google drive's end.

visit drive.google.com
click the top right hand gear.
click manage apps
CKP -> options -> disconnect.

Then for good measure, goto CKP settings and 
1. Deauthorize google drive.
2. Go to settings/stored_data and delete databaseUsages, selectedDatabase
3. Reauthorize google drive.

**Comment by npgauth** [comment]
I tried to do that and also completely removed and reinstalled the extension. Still no luck--the request for permission just never pops up. Darn. Your extension is so useful! I guess I could try wiping and reinstalling Chrome?

**Comment by suBDavis** [comment]
That seems like overkill.  

You should however disable every other extension you're using, as something may be tampering with pop-ups.  I find that sometimes chrome issues can be killed by deleting your local user profile.  Warning: this will kill your login sessions, history, etc...

Windows: something something %APPDATA%
Mac: ~/Library/Application Support
Linux: ~/.config/google-chrome

If none of that works, you'll have to wait for the developer.

**Comment by suBDavis** [comment]
Any luck, @npgauth ?

**Comment by npgauth** [comment]
Sorry for the slow reply. I didn't have to delete any of the local user profile, but it magically started working today. I wonder if some of the problems stemmed from the google drive phishing attack that was in the news last week? Either way it is fixed on my end now. Thanks for your help! Nick

**Comment by subdavis** [comment]
@npgauth Glad it got fixed!  Once you're sure everything is good, mind closing the issue?  Thanks.

**Comment by npgauth** [comment]
Done. Thanks for your help and a great project!

**Comment by zefie** [comment]
I too am having this issue, and have tried everything listed here besides wiping my entire user profile. It started when I launched and synced Chrome on a Mac, if that helps. Reinstalling CKP triggers the dialog to allow extension access to the google domains, then displays the message to accept Drive access but never launches the popup. Can't see any extensions I have that are enabled that would block it (turned off ublock and such). A small workaround the dev could do is add a link to manually launch the token auth url. Until then I am unable to use CKP :(
