### ISSUE TITLE
Do I need to update KeePassHttp?

### ISSUE THREAD

**Issue by vinhphamh** [perfectapi/CKP#169]
I use the KeePass application on Windows and the CKP Chrome extension.  When I start the KeePass application, it states that a new version of the KeePassHttp plugin is available.  Do I need to update that plugin?  How?  Thanks.

**Comment by DukeyToo** [comment]
That plugin is unrelated to CKP.  You do not need to update it for CKP to work.

**Comment by vinhphamh** [comment]
Thanks!
