### ISSUE TITLE
Add folder icons

### ISSUE THREAD

**Issue by jpvantuyl** [perfectapi/CKP#17]
I like that the list of passwords is a flat list but it hides the hierarchical structure in the Windows KeePass client.

![image](https://cloud.githubusercontent.com/assets/1139835/6161182/fe47a4c4-b221-11e4-9ab9-75f1e691f35c.png)

It'd be nice to also show the icons, perhaps to the left of the ChromeKeePass entry, to add that context back.

![image](https://cloud.githubusercontent.com/assets/1139835/6161222/a570ab38-b222-11e4-9f5b-9c23a0856e05.png)

**Comment by DukeyToo** [comment]
Closing (fixed)
