### ISSUE TITLE
DropBox support broken since 2017.5.28

### ISSUE THREAD

**Issue by kevin39** [perfectapi/CKP#176]
Hi,
Everything was working fine until this update.

It's now unable to load files from Dropbox, each unlock results in this error : 
_First argument to DataView constructor must be an ArrayBuffer_

I did : 
- Logout/Login frop Dropbox : Same error
- Uninstall/Reinstall chrome extension : Same error
- Loaded files from filesystem : No error (it works)

Best regards,
Kevin

**Comment by DukeyToo** [comment]
I am unable to reproduce with version 2017.5.28 of CKP.  

There were changes in the Dropbox API, requiring CPK to change to match.  However, these changes are working for me on multiple devices, without any errors.

Do you have any more information you can provide to help debug?

**Comment by kevin39** [comment]
Maybe this can be related to my database's path ? There is an accent on letters.

Path to my kdbx : 
/Dossier de l'équipe 1001PNEUS/Mots de passe/Généraliste.kdbx

**Comment by kevin39** [comment]
Juste saw your edit.

Here are some informations : 
angular.min.js:94 POST https://api-content.dropbox.com/2/files/download 400 (Bad Request)

Reply from Dropbox : 
Error in call to API function "files/download": HTTP header "Dropbox-API-Arg": could not decode input as JSON

I think I'm right about the path, I think it's an encoding problem : 
Dropbox-API-Arg:{"path": "/Dossier de l'%E9quipe 1001PNEUS/Mots de passe/G%E9n%E9raliste.kdbx"}

**Comment by DukeyToo** [comment]
Yeah, definitely something to do with the characters.  Can fix.

**Comment by DukeyToo** [comment]
Release 2017.5.29 should fix.  Thanks for reporting this!

**Comment by kevin39** [comment]
No sorry, same behavior... Extension is up to date (2017.5.29) but the same bug occurs.

**Comment by kevin39** [comment]
I found this, maybe it will help you : 
https://www.dropboxforum.com/t5/API-support/International-characters-in-filenames/m-p/175753/highlight/true#M6950

**Comment by DukeyToo** [comment]
Release 2017.5.30 should fix.  I tested it with your filename and it worked for me.

**Comment by kevin39** [comment]
It's working ;)

Thank you
