### ISSUE TITLE
CKP is shown Disabled in toolbar

### ISSUE THREAD

**Issue by tvrhossain** [perfectapi/CKP#181]
Why is CKP extension always disabled in my chrome bar? Although in extension manager, its Enabled, but in chrome toolbar above, it remains hidden,disabled. Pls see the pic here - http://tinypic.com/r/6878te/9

**Comment by DukeyToo** [comment]
It will be disabled unless a password field is detected on the current page.  Is that the behavior you are seeing, or is it always disabled even when there is a password to be filled out?

**Comment by DukeyToo** [comment]
No response, closing
