### ISSUE TITLE
Database not found in Google Drive on new Chromebook

### ISSUE THREAD

**Issue by ikelly** [perfectapi/CKP#186]
On a new Samsung Chromebook Pro the extension is authorizing but failing to find my database in Google Drive. The database is located in My Drive, not in a subfolder, and it has a .kdbx filename. I've previously used the same database on other Chromebooks as well as in Chrome on Linux with no problems. I was able to download the database to the file system and upload it to local storage and it works this way, but of course that means I'm not getting updates automatically.

**Comment by subdavis** [comment]
@ikelly - Thanks for opening this issue.  Is there anything special about the KDBX file name?  Does it contain spaces or any sort of non-ascii characters?  If so, please upload a renamed copy to your google drive called something like `text.kdbx`

I also found a similar old issue, #113.  Could you try to use a desktop version of KeePass to make a brand new database, upload it to google drive using the WEB interface (your google drive client may have corrupted the file), and see if you can access it?

**Comment by ikelly** [comment]
@subdavis - The filename is entirely ASCII letters but it does start with a capital so just in case I tried renaming it within Drive to be all lowercase -- surprise, now it works! I then reverted the name change and it still works, so I'm no longer able to reproduce the issue.

I don't think it was a data corruption issue though since literally all I changed to fix it was the filename, and I didn't even re-upload it to Drive (I don't use the desktop sync client at all). Also, even though I was unable to find it on the new Chromebook, in the meantime the same database continued functioning in other Chrome instances.

I did also edit the database in Keepass2Android recently and I'm not 100% certain that I actually tried reproducing the issue after that and before the renaming test, so it could be that this is what fixed it. However, I tried re-uploading the previous revision from Drive as a separate file and still could not reproduce the issue.

**Comment by subdavis** [comment]
@ikelly thanks for the update.  I wish it were reproducible, as there have been several cases like yours.  It may have been anything, including a bug with the Drive API.

Please close the issue for now, and if it comes back, we can reopen it.  Cheers.

**Comment by mikeries** [comment]
I've been using CKP with a database on my google drive for years now on various version of windows with no issues.  A couple weeks ago, it stopped being able to read my database.  I uninstalled CKP and installed CKPX.  CKPX says it has connected to my drive but wasn't able to find any database files.

**Comment by subdavis** [comment]
Hiya @mikeries 

Thanks for the report.  If you continue to use CKPX, let's continue this discussion on that issue tracker.

That being said, let's try a few things.

1. Try creating a copy of the file in your google drive.  Does CKP(X) see that?
2. If not, let's create a copy using your desktop app.  Do a Save-Database-as and make a copy of your db with a new name in your google drive folder.  Does that work?  
3. If you're feeling up to it, open the chrome options pane, and disable and re-enable google drive authorization.  If your database doesn't appear, open the chrome developer tools and see if there are any errors in the console.  right click on the options pane and click "inspect".  The error will be in a tab called "console".

**Comment by mikeries** [comment]
I made a copy using 'Save As' from the desktop app and that worked.  Thanks!

Mike
