### ISSUE TITLE
Save passwords on browser or save the master password ?

### ISSUE THREAD

**Issue by Cuicuiman** [perfectapi/CKP#198]
Hi.

I don't know if I am in the right place to ask a general security question so ...
I want to be safe but i also want my navigation to be convenient. I go on my fb/twitter and multiple others sites everyday, i just can't type my password everytime.

So i would like to know what is the safest option ;

- Let my browser remember all my passwords
- Or using CKP with keepass with remembered master key so i don't have to type everytime i browse

Thank you for your help.

**Comment by subdavis** [comment]
@Cuicuiman that's an awesome question, and it has a pretty straightforward answer:

let your browser remember all your passwords.  CKP can only keep your database open by caching a copy of your mangled master key on disk.  This key is a hash of your master password and keyfile, so looking at your master key won't reveal your master password, but it can be used to unlock your keepass database.

Cheers!

**Comment by Cuicuiman** [comment]
Thanks for your help ;)
