### ISSUE TITLE
In database with hundreds of entries on Mac OSX 10, manual list shows empty

### ISSUE THREAD

**Issue by DukeyToo** [perfectapi/CKP#26]
Find manually doesn't list any entries
Posted by A Google User	
When I open a kdbx file and theres no match to the current site, I choose 'find manually' to browse the entire list, but it's empty (the file has several hundred entries)
Reply
Application version: 2015.3.24.3
Client version: 5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
Reported date: 4/17/15 3:03 PM
Reported by: A Google User

**Comment by ciaran-byrne** [comment]
I was the one who posted this, happy to help with any debugging

**Comment by DukeyToo** [comment]
Thanks!  When this happens, does it still work to type the name of the entry and find it, or does the list stay blank when that happens?

**Comment by ciaran-byrne** [comment]
The list remains blank, even if I type in the name of a known entry

**Comment by DukeyToo** [comment]
I was unable to reproduce, but I have released a new version 2015.4.26.1 with a redesigned manual search.  Please let me know if this fixes the problem, thanks!

**Comment by ciaran-byrne** [comment]
Hmm, just tried it there with the latest 2015.4.27, with the same result on MacOSX - no entries in the list. I'll do some more debugging locally on my side, in case it's my .kdbx file

**Comment by DukeyToo** [comment]
Yes, there must be something unusual about one of the entries in your file.  Still a bug in CKP though.

It would help me to debug it if you go to the empty list and right click on it and select "Inspect Element".  This will bring up the dev tools, and if you click on "Console" there is probably some error there.  A screenshot of that would be great :)

**Comment by ciaran-byrne** [comment]
It's my file, keepassService can't parse it properly. For info, I have both custom icons in my file, along with binary attachments. I'll keep digging.

![ckp_2015-04-29](https://cloud.githubusercontent.com/assets/5129669/7390470/8eb8fcda-ee70-11e4-82b6-a2a4f326cae6.png)

**Comment by ciaran-byrne** [comment]
Yep, it's the binary attachments, which don't seem to be removed from the database, even though I removed them from the entry. I exported the db, manually removed the Binary entries in the XML file, and re-imported into a new DB, which now populates the list correctly. In case you want to test it, I had 524 entries, 39 groups, and 13 attachments/binaries.

**Comment by DukeyToo** [comment]
Ah, I think I understand what happened - when a kdbx database grows too large then it is split into multiple blocks, and the current code only handles the first block :(  

Now that I know what to do, the fix should be simple.  Thanks for all your help and for reporting this!

**Comment by ciaran-byrne** [comment]
No problem, and thanks! Confirming the latest build 2015.4.29 worked with both my files (one with the binaries, and one without)

**Comment by ciaran-byrne** [comment]
Just to clarify when I say it worked on my file, I was using local git cloned copy from you repo, which I loaded as an unpacked extension - the store version is still not working for my file, so I'm just assuming it's not the latest version at the moment

**Comment by DukeyToo** [comment]
Thanks for clarifying, I thought that must have been it.  As you surmised, the git version is newer than the one on the store.  Most likely I will publish it this weekend.
