### ISSUE TITLE
Can no longer keep database open longer, can no longer see list of database entries

### ISSUE THREAD

**Issue by libenjamang** [perfectapi/CKP#29]
2 issues that started concurrently:
1) Unable to keep database open longer, despite checkbox under Advanced Options being ticked
2) Unable to see list of database entries when searching manually. Even when searching for a known entry, no entry is shown

I started using the extension maybe 3-4 days ago and initially did not have either of these problems. Just noticed these issues 1 or 2 days ago. I tried to remove and reinstall the extension but with no luck.

**Comment by DukeyToo** [comment]
Thanks for reporting this.  Can you provide some additional info, specifically, Chrome version, CKP version, type of KeePass database (KDB vs KDBX)?

**Comment by libenjamang** [comment]
Hi, my CKP version is 2015.5.1. I'm using a kdbx database stored on Google
Drive. It's a small database with under 10 entries. I get this problem on
my Chromebook running Chrome OS version 42.0.2311.134, but not on Chrome on
my desktop PC.

**Comment by DukeyToo** [comment]
Reproduced, and fixed in 2015.5.4.  I had introduced an enhancement to make the "Use encrypted cache to keep database open longer" feature more resistant to attack, but for some reason the new crypto feature I used (PBKDF2) is not supported on ChromeOS.  :(

Thanks again!
