### ISSUE TITLE
DropBox integration

### ISSUE THREAD

**Issue by kubino** [perfectapi/CKP#34]
Hi, I have found in your documentation you are already supporting Dropbox. Found it in develop branch, so I tried, but I always get like empty white page after granting ckp application (instead of some file picker). In Chrome console I can see <code>Uncaught ReferenceError: extensions is not defined</code>  .  Do you have an idea what I am doing wrong ?  I Thx in advance.

**Comment by DukeyToo** [comment]
Not sure ... feature is not ready for prime time, but it should work.

Do you have any KeePass files in dropbox?  If there are no files found then it probably shows a blank list.

**Comment by DukeyToo** [comment]
I have an update to Dropbox integration in the https://github.com/perfectapi/CKP/tree/feature-premium-features branch.  That probably fixes the issue.

**Comment by DukeyToo** [comment]
Dropbox integration is now in the live build on the web store.
