### ISSUE TITLE
chrome.commands integration

### ISSUE THREAD

**Issue by 3mb3dw0rk5** [perfectapi/CKP#36]
Is it possible to integrate the chrome.commands API (https://developer.chrome.com/extensions/commands) so we can define shortcuts maybe for just opening the CKP popup for a password search etc.

**Comment by DukeyToo** [comment]
I would accept a pull request that did this, but I am unlikely to work on it myself.  

My preference for this need is to release a CKP App (different than the extension) where you would have a more KeePass-like experience for looking up and adding/editing passwords.  That is a lot of work though, so it won't happen soon.

**Comment by 3mb3dw0rk5** [comment]
Ok i will check this.
