### ISSUE TITLE
entry.keys.push is not a function

### ISSUE THREAD

**Issue by DukeyToo** [perfectapi/CKP#42]
Hello, when I try to open a file (Google storage or locally uploaded), I have the following error : entry.keys.push is not a function Dot you know what I have to do ? Kind regards, Simon

Application version: 2015.5.27
Client version: 5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
Reported date: 6/10/15 11:19 PM
Reported by: A Google User

**Comment by DukeyToo** [comment]
I suspect that the particular kdbx file has a custom "keys" property and that is overwriting the keys property that CKP uses internally when parsing the file.

**Comment by Banandrew** [comment]
Hey, I've just started using the extension, and got the same error upon unlocking my database from Dropbox. Is there anything specific that I should report?

**Comment by DukeyToo** [comment]
Must be the same issue, but I thought this was fixed.
