### ISSUE TITLE
Using Dropbox

### ISSUE THREAD

**Issue by iwisi** [perfectapi/CKP#53]
Do I have to do anything special to use Dropbox to store my password file?  I notice it's a "premium feature", and I can't get it to display a list of files to allow me to choose my password file.  It appears to  allow me to log on and off.

**Comment by DukeyToo** [comment]
It should work the same as the Google Drive integration - once you've logged on, the file is available to choose when you click the KeePass icon in the address bar.  You should also see it listed on the settings page.

**Comment by iwisi** [comment]
Google Drive works fine, however when I right click the icon in the address bar, then select Options/ Keepass Databases/ Dropbox the grey Login button appears. I click that and log in, then "Selecting list of files" flashes up (yellow background) and is immediately replaced by the Logout button.  I don't get a chance to select any Keepass databases, although I have 3 in my Dropbox.  This happens both on Chrome OS and Linux Mint.  I'm running  Chrome 44.0.2403.130 (64-bit)  on Mint.

**Comment by DukeyToo** [comment]
Ok.  I think Dropbox is not showing .kdb (KeePass 1) files.  Does that match your scenario?

**Comment by iwisi** [comment]
Yes, it does.  They are .kdb ( Keepass1) files.  I'm actually using KeepassX. 
From the KeepassX FAQ:  "KeePassX currently uses the KeePass 1.x (Classic) password database format as the native format. ... KeePass 2.x database format is not supported."

**Comment by DukeyToo** [comment]
Ok, I will fix

**Comment by iwisi** [comment]
Thanks - I appreciate it.

**Comment by iwisi** [comment]
Thanks Steve - I confirm it works.  Great product (and support!)
