### ISSUE TITLE
Password file remains open after several hours

### ISSUE THREAD

**Issue by swestcott** [perfectapi/CKP#57]
Under advanced settings "Use encrypted cache to keep database open longer" is NOT selected.

After unlocking my password file it remains open for several hours (currently at 6hrs). My understanding of the extension settings is that it should lock ~10 seconds after the pop-up is closed.

**Comment by swestcott** [comment]
Extension version: 2015.8.13.2
Chrome: Version 45.0.2454.85 (64-bit)
OS X: 10.9.5

**Comment by DukeyToo** [comment]
It's not so much that it locks after 10 seconds, it is that Chrome is supposed to unload it from memory.  If it is not unloading, then that is a bug in Chrome.

In any case, I cannot reproduce this locally, but I'll keep this report open as a bug in CKP.  (I can't control when Chrome unloads the extension, but I can add a feature that forces CKP to lock again after some time).
