### ISSUE TITLE
Option to auto-refetch filesystem databases into Chrome local storage

### ISSUE THREAD

**Issue by charlesk** [perfectapi/CKP#60]
Basically asking for CKP's Dropbox / Google Drive resync feature to work for filesystem databases too. That way users who sync their file with another service (e.g. SpiderOak, Seafile, OwnCloud) will see CKP pick up password changes automatically.

Maybe the database's import time could be compared against the file's mtime to see if an update is needed in the Chrome local storage?

**Comment by DukeyToo** [comment]
Sorry this is not possible.  For security reasons Chrome does not allow the extension to access the filesystem, so the only way this can work is by using 3rd party that stores in a cloud, such as Dropbox or Google drive.
