### ISSUE TITLE
Unable to use a keyfile that works with KeePass2Android

### ISSUE THREAD

**Issue by 4regt4** [perfectapi/CKP#61]
Hi, noob here.
I have been testing KeePass2Android, and so far all is going well. Storing the password.kdbx on Google Drive, and successfully been sharing it with KeePass CKP on my Chromebook. Until.....

I decided to try using a keyfile. Created a simple text keyfile (just the 4 characters "test", not even a "return" at the end) on one Android device, sent it via Bluetooth and ES File to another Android phone. All is OK.  Both Android devices sync'd, and the password file opens fine using the keyfile on both. Tested it using password only to make sure that the database was requiring the keyfile. But I can't get the keyfile option to work on the Chromebook. I copied the keyfile various ways (USB cable from Android to CB, email attachment, via Google Drive, bluetooth) to the Chromebook's "Download" folder and selected the file in CKP's settings. I get an error in the Chromebook app every time when I try to open the password file. "Incorrect password or key file". I even tried putting the keyfile on Drive (yeah, putting the database and the keyfile in the same place kind of defeats the purpose... but I'm just testing at this point), but still no-go.  Tried using the filename suffix ".key", just in case...  The file has no formatting, shows as 4 bytes in size.
Ideas?
Thanks,
Hans.

**Comment by DukeyToo** [comment]
So to be clear, this is using the keyfile only option, or keyfile + password?

Also, is this a .kdb or a .kdbx file?

**Comment by 4regt4** [comment]
Hi, thanks.
Started with password only (which worked fine in both Android and CKP), reset the master password adding a keyfile in the Android app - so using the password+keyfile there.  But I can't seem to get CKP to recognize the same keyfile.  I added the keyfile in the settings of CKP.  I noticed in Android that there is specifically an option at login to specify "password+keyfile", but is there one in CKP?  I only see the field to enter "Master Password".  I'm assuming that it knows that a keyfile is involved, given that I specified one in the setup options, no?  It's a .kdbx file.
Thanks,
Hans.

**Comment by 4regt4** [comment]
PS:  I just tried the same .kdbx and keyfile in the Windows "portable" ver 2 and it worked fine.  i.e., I copied the keyfile to a USB stick from the Android device and pointed the Windows version to it.

Hans.

**Comment by DukeyToo** [comment]
Ok, I think I know what happened.  If you go to CKP options, Stored Data tab, click on the delete button next to "databaseUsages".  This will reset CKP's knowledge on your password database, and you will be able to choose the keyfile the next time that you open it.

**Comment by 4regt4** [comment]
Yes, that worked.  

Thanks,
Hans.
