### ISSUE TITLE
Keyfile not recognised

### ISSUE THREAD

**Issue by scaine** [perfectapi/CKP#73]
When I upload my keepass2 kdbx file, then specify my keyfile, it appears to take both entries, but when I later click on the padlock to access CPK for a given site, the drop down only shows the password entry and no keyfile.

This only started happening in the past week or so, coinciding with a new message that manual uploading of kbdx files is "deprecated". But since my only alternative is the the dropbox method, and that requires access to every file in my dropbox folder, I won't use that option (see issue #63).

So maybe the change to deprecate uploading has also disabled support for keyfiles on those uploads?

Sadly, this rules out CPK for me until either this, or issue #63 is resolved. I can do a bit of python coding, but never used js before, so I'm afraid I can't help with this directly.

**Comment by DukeyToo** [comment]
I am not able to reproduce this problem.  

There have been no changes to the functionality of key files.  Uploading of database files is "deprecated", but you can still get to the functionality by clicking the button on the deprecation message.

**Comment by scaine** [comment]
Yeah, sorry - I notice that my home PC still works perfectly, same O/S, same browser and presumably same version of CPK. No idea what's causing this behaviour on this PC, but it's clearly an issue with this PC only and not CPK generally. Perhaps it's related to some underlying cache setting?

Happy to close this, but if there's value in troubleshooting the issue (I'd appreciate the help), then any suggestions on how to do so would be appreciated.

**Comment by scaine** [comment]
And it's fixed. I went to CPK's "Advanced settings" and noticed that the database entry had a blank "keyfile" entry under it, despite there being a keyfile entry separately. I deleted everything in the Advanced Settings apart from the "UseDiskCache True" entry, then re-added my database and keyfile.

After unlocking, everything worked perfectly.
