### ISSUE TITLE
Soundcloud.com sign in popup doesn't show CKP icon in URL bar

### ISSUE THREAD

**Issue by bes** [perfectapi/CKP#77]
Step by step:
* Go to https://soundcloud.com/
* Click "Sign in" at the top right
* Sign in popup shows up - *no CKP icon visible*

<img width="497" alt="ckp_no_icon" src="https://cloud.githubusercontent.com/assets/85731/12205983/af246568-b63e-11e5-82bd-c1d0db284e71.png">

**Comment by DukeyToo** [comment]
This is because the login is a completely separate browser window without the extras like popup action icons.  Unfortunately there is no way to support this, sorry.
