### ISSUE TITLE
Ignore 'backup' folder

### ISSUE THREAD

**Issue by yacoob** [perfectapi/CKP#81]
Keepass (or at least KeepassX) keeps a `backup` folder, where it stashes old versions of passwords after each edit. CKP shows search results across all folders - which means that if you search for `foo`, you'll see the latest version at the top and a number of backup entries below. Perhaps it'd be useful to filter that folder out?

**Comment by DukeyToo** [comment]
Actually, it is supposed to work this way already.  My info says that the folder should be `Backup` though, with a capital `B`.  See the keepassx code at https://github.com/keepassx/keepassx/blob/5a5928792722961245888358f04cd8fb0114024e/src/format/KeePass1Reader.cpp#L219

In your example then, the "backup" folder was definitely created by KeePassX?

**Comment by yacoob** [comment]
Yup. The only unusual thing would be that it was created by KX1, and I've converted the file to `.kdbx` to use it with KX2. But as far as I can tell, the only criteria is the name, right?

To ask a different question - is there a way to "inspect" the details of the entry in CKP itself so I can pinpoint them? If not, I'll just edit the old entries in a way that allow me to distinguish them.

**Comment by yacoob** [comment]
Thanks for a fix.
