### ISSUE TITLE
xlink:href="#icon-cog" doesn't work and jumps with me to first tab

### ISSUE THREAD

**Issue by freed00m** [perfectapi/CKP#87]
Minor UI issue, the settings icon in ball popup doesn't work.
If you've already fixed it please disregard and looking forward to your next release :)

---

No incognito.
Cromium Version 49.0.2623.87 (64-bit)
CKP - KeePass integration for Chrome™ 2015.11.23

![2_001](https://cloud.githubusercontent.com/assets/9461698/13935576/50ac495c-efb8-11e5-862c-dccbc1a05991.png)

EDIT: only flag set was Material design  #top-chrome-md

**Comment by DukeyToo** [comment]
Verified, it also does not work for me.  As a workaround until fixed, you can right click on any extension icon to get to the options menu.
