### ISSUE TITLE
chrome.p.storage.remove is not a function

### ISSUE THREAD

**Issue by CdtDelta** [perfectapi/CKP#89]
CKP Version 2016.3.23

Version 50.0.2661.37 beta (64-bit)
Ubuntu 14.04 LTS 64-bit

KeePass file is stored on Google Drive

Steps to reproduce issue:

1) Go to site requiring password
2) Click on CKP extension
3) Get prompted for and enter password
4) Red box with "chrome.p.storage.remove is not a function" appears below password window

Passwords for the URL are not being shown, you're just prompted for your password again.

I just tested the same plugin on my Ubuntu 15.10 64-bit laptop as well, running Chrome Version 49.0.2623.87 (64-bit) and have the same issue.
Also tested on my Chromebook running beta channel, version 50.0.2661.32 beta (64-bit) and I do NOT have the issue.

**Comment by cmsliepen** [comment]
same error message here, just after new update.

Using:
Chromebook Pixel
Version 49.0.2623.95 (64-bit)
Platform 7834.60.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.174.0

Channel: stable

**Comment by warmana** [comment]
This problem also observed on Fedora 23 64-bit, running Chrome (stable) version 49.0.2623.87 (64-bit) with CKP version 2016.3.23.

**Comment by chrisLeeTW** [comment]
This problem also observed on Mac OSX 10.10.5 64-bit, running Chrome (stable) version 49.0.2623.87 (64-bit) with CKP version 2016.3.23.

**Comment by DukeyToo** [comment]
Pushed a new version that should fix.  Monitoring...

**Comment by cmsliepen** [comment]
version 3.24 doesn't solve the problem for
Using:
Chromebook Pixel
Version 49.0.2623.95 (64-bit)
Platform 7834.60.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.174.0

Channel: stabl

**Comment by warmana** [comment]
I am still seeing the error with Fedora 23 64-bit, running Chrome (stable) version 49.0.2623.87 (64-bit) and the new CKP version 2016.3.24.
