### ISSUE TITLE
chrome.p.storage.remove is not a function - Issue still present

### ISSUE THREAD

**Issue by CdtDelta** [perfectapi/CKP#91]
Issue is still present in new version.  Did a force update of extension this morning at 8:52AM CDT.

CKP Version 2016.3.24

Version 50.0.2661.49 beta (64-bit)
Ubuntu 14.04 LTS 64-bit

KeePass file is stored on Google Drive

Steps to reproduce issue:

1) Go to site requiring password
2) Click on CKP extension
3) Get prompted for and enter password
4) Red box with "chrome.p.storage.remove is not a function" appears below password window

Passwords for the URL are not being shown, you're just prompted for your password again.

I just tested the same plugin on my Ubuntu 15.10 64-bit laptop as well, running Chrome Version 49.0.2623.87 (64-bit) and have the same issue.

**Comment by DukeyToo** [comment]
Reproduced.  Will fix asap.  You can workaround by choosing one of the "remember" options

**Comment by DukeyToo** [comment]
Fixed in 2015.3.25

**Comment by CdtDelta** [comment]
Fixed, tested on all the machines I had issues with.
