### ISSUE TITLE
chrome.p.storage.remove is not a function when unlocking the .kdbx 

### ISSUE THREAD

**Issue by nitrnitr** [perfectapi/CKP#92]
Can't unlock the database, this started happening today to me and a friend of mine. Maybe with last update or with a Chrome update, don't know.

https://www.dropbox.com/home/Screenshots?preview=Screenshot+2016-03-24+10.43.12.png

**Comment by patriciomacadden** [comment]
Same thing happening to me!

**Comment by DukeyToo** [comment]
Reproduced.  Will fix asap.  You can workaround by choosing one of the "remember" options

**Comment by DukeyToo** [comment]
Fixed in 2015.3.25
