### ISSUE TITLE
chrome.p.storage.remove is not a function

### ISSUE THREAD

**Issue by Denwf** [perfectapi/CKP#93]
Hello! 
After entering the password, the following message appears: "**chrome.p.storage.remove is not a function**".
Google Chrome 48.0.2564.109 m
KeePass 2.31
CKP - KeePass integration for Chrome™ 2016.3.23

**Comment by nitrnitr** [comment]
Yea i've just opened another ticket for this. This is definitely a bug!

**Comment by Denwf** [comment]
CKP - KeePass integration for Chrome™ 2016.3.24 updated, the problem persists.

**Comment by mojason-81** [comment]
I'm having the same issue.  I use this on two different machines.

Ubuntu 14.04
Google Chrome 49.0.2623.87 
CKP  2016.3.24

Ubuntu 15.10
Chromium (sorry, don't have the version number)
CKP (assume 2016.3.23/24)

**Comment by DukeyToo** [comment]
Reproduced.  Will fix asap.
