### ISSUE TITLE
chrome.p.storage.remove is not a function

### ISSUE THREAD

**Issue by dkm77** [perfectapi/CKP#94]
Hi,
today I noticed that I am receiving the error message "chrome.p.storage.remove is not a function" when trying to unlock my database.
A few days ago it was still working.

I already tried reenabling the extension and adding my account again (using Google Drive). Also checked that Chrome is up to date.
I am using a KeePass 1 database, if that matters for this issue.

Thanks,
Dennis

**Comment by nicolassmith** [comment]
Had the same issue. But I just updated/restarted my chromebook and the issue has gone away.

**Comment by DukeyToo** [comment]
An update to latest extension version should fix this.

**Comment by dkm77** [comment]
Thanks, didn't notice this was already open. Works fine again now!
