### ISSUE TITLE
Local Storage Deprecation

### ISSUE THREAD

**Issue by mostlyspam** [perfectapi/CKP#97]
Hello.

Not really an issue.  More of a request.

Please do not deprecate the local storage option.  It is very useful for those of us that never send or store keepass files over the net.  There are strong security reasons to never put a keepass file online.

thank you

**Comment by mostlyspam** [comment]
I am not sure why the authors feel that the users expect databases to stay current automatically.  Most uses of keepass are probably read only anyway.  Keeping a reference set of keepass files on a USB drive is fairly normal and considerably safer than storing them on Dropbox, Google Drive, or other online storage solutions. 

As the only reasonable option so far on keepass usage in chrome (and chromebooks) it seems reasonable to expect that the authors have a particularly keen understanding of security and privacy.  Online storage of anything is neither secure nor private.



=-=-=-=
CKP no longer supports this feature because it cannot work the way that people expect. 
=-=-=-
Loading files this way is ONLY suitable for old files that are never updated. Please use Google Drive or Dropbox or OneDrive for the best CKP experience!
=-=-=-=
I realize that files stored in this way won't update themselves

=-=-=-=

**Comment by DukeyToo** [comment]
I have no plans to actually remove the feature.  I use it myself too, in some scenarios.

It just falls short of my and other users' expectations, because ideally the feature would be able to read the file from a USB drive directly, but that just cannot be done by a Chrome Extension.

**Comment by dodtsair** [comment]
Since the core feature that I would use is being deprecated, I can not justify adopting this extension.  I'll look else where for my solutions.

**Comment by Jonathan34** [comment]
Indeed, really unfortunate. CKP seemed promising. I have my own personal cloud with my own synchronization mechanism between my devices so i use the local file storage so my password are where i want them to be.
